appiumServer: "http://127.0.0.1:4723"
platformVersion: "16.5"        # 设备iOS版本
deviceName: "iPhone14"    # 设备名称
udid: "auto"  # 设备UDID
app: "live.fanatics.FanaticsCollect-Development"   # 或使用bundleId
noReset: true
includeSafariInWebviews: true
useNewWDA: False
